### ISSUE TITLE
Absolute path issue on Linux when auto converting dtb to dta

### ISSUE THREAD

**Issue by mtolly** [PikminGuts92/Mackiloha#10]
Heya, I happened to notice a small issue on Linux with arkhelper + dtab.
Basically if I extract an ark, use `-s`, and pass an absolute path for the extract folder, the converted .dta files are not being placed in the intended extract folder, but rather that absolute path is reinterpreted to be relative to my working directory.
So for example if I run `arkhelper ark2dir -s -a /tmp/GEN/MAIN.HDR /tmp/GEN/extract` from my home folder `~`, most of the output will be correct, but I will also get a new folder `~/tmp/GEN/extract` which contains just the .dta files.
The log looks like this:

```
...
Wrote "/tmp/GEN/extract/world/theatre2/streams/crowd_v4_4good.vgs"
Wrote "/tmp/GEN/extract/world/theatre2/streams/encore_v5_intro.vgs"
Wrote "/tmp/GEN/extract/world/theatre2/streams/encore_v5_outro.vgs"
Wrote "tmp/GEN/extract/(..)/(..)/system/run/char/char_objects.dta"
Wrote "tmp/GEN/extract/(..)/(..)/system/run/config/arkbuild-sliptest.dta"
Wrote "tmp/GEN/extract/(..)/(..)/system/run/config/arkbuild.dta"
...
```

So the slash at the start gets removed. I haven't verified but I suspect it's this regex which is the problem, it seems like it will only start matching just after the initial slash when trying to drop the `gen` folder:
https://github.com/PikminGuts92/Mackiloha/blob/cb244c13b4506bfe5a9a20ecc8e739e07b999da4/Src/UI/ArkHelper/Apps/Ark2DirApp.cs#L79

**Comment by PikminGuts92** [comment]
Sorry for the late reply. It appears your assumption was correct about the regex. I updated the expression to capture optional leading slash character. I can't currently test on a linux machine but the same behavior existed on Windows and I verified the fix there.

You can download a build for it on [AppVeyor](https://ci.appveyor.com/project/PikminGuts92/mackiloha/branch/master/artifacts) until I publish a regular GitHub release.

<img width="308" alt="devenv_YA4x4Q8nnD" src="https://user-images.githubusercontent.com/15707039/155457575-dfb7271d-2f91-42ed-9128-1d5a2d7b76da.png">
<img width="674" alt="VsDebugConsole_Cf9vMoIUyH" src="https://user-images.githubusercontent.com/15707039/155457590-2a1dede2-9c84-4b6b-9dfb-38a8a12ff297.png">
