### ISSUE TITLE
Amplitude (2016)

### ISSUE THREAD

**Issue by DanTheMan827** [PikminGuts92/Mackiloha#12]
This is a V9 ark, but it is XOR'd with 0xFF.

The game also requires a very specific key that differs between the ps3/ps4 versions, but that's not really an issue with this code.

I've validated that forcing a 0xFF xor on the header produces a file that the game accepts, but not without.

**Comment by DanTheMan827** [comment]
I've added some code to force it to use specific data, but I don't know if you want this or not
https://github.com/DanTheMan827/Mackiloha/tree/overrides

There's also a amplitude-ps3 branch that I made, but it won't work for ps4 because the extra data is different along with the key

**Comment by PikminGuts92** [comment]
Gonna close this as irrelevant. While this library does have partial support for Forge files, support for it is not a primary concern.
