### ISSUE TITLE
[Feature Request] Support for building "Broken" v4 arks

### ISSUE THREAD

**Issue by LlysiX** [PikminGuts92/Mackiloha#14]
I tried doing as suggested in https://github.com/PikminGuts92/Mackiloha/issues/11#issuecomment-1049452831 to rebuild a Rock Band 1 Xbox 360 TU5 patch ark using ark version 3, unfortunately, even when run with a no checksum patched xex, all that is shown is a black screen.

This screenshot from xenia, hardware gave similar results:
![image](https://user-images.githubusercontent.com/79173634/209774086-716cebb1-126d-4fa8-b137-be8c69662a51.png)
The xenia log shows a spam of the line `i> F8000028 xeRtlNtStatusToDosError C0000008 => 6`. I'm not sure exactly what it means, I feel like it should be causing a fatal error crash, all I know for sure is it refuses to load the rebuilt v3 patch ark.

As expected, running with a xex that wasn't no checksum patched resulted in a disc read error:
![image](https://user-images.githubusercontent.com/79173634/209776001-8dcaaa28-e054-4a77-a309-bbacfc0f52a3.png)

I tried to use a hacky workaround, using a blank v3 patch ark and pushing the patch files into main by extracting both, replacing duplicates with patch files, and rebuilding main as v3. It worked. However, many glitches came up, the worst of which was found in a short amount of testing, crashing when attempting to create a character for band tour and solo tour.

**Comment by PikminGuts92** [comment]
Fixed in #15
