### ISSUE TITLE
Not sure if this is the right place to report, but replacing MOGGs in DC3 main_xbox.hdr breaks song

### ISSUE THREAD

**Issue by wintyre01** [PikminGuts92/Mackiloha#16]
So I just started working on a project to decensor songs on Dance Central 3's disc and I'm currently running into the issue where when I load in the updated main_xbox.hdr and ark files, they leave the song on an infinite loading screen. I'm currently using Starships as my test subject for this. I'm also using the same method for repacking Rock Band 3's files as I was assuming DC3's was of somewhat of a similar vein. If any help could be provided if possible please, it's appreciated.

**Comment by PikminGuts92** [comment]
Yeah, this isn't the appropriate place for that issue. If game boots up fine then generally that means ark files were packed correctly. It's not an issue with the tool.

Maybe verify replaced mogg channel count matches original.
