### ISSUE TITLE
Guitar Hero II PS2 - Repack of character anim milo with no change causes stall in PCSX2 (and likely hardware)

### ISSUE THREAD

**Issue by jnackmclain** [PikminGuts92/Mackiloha#7]
I found myself needing to edit the contents of funk1_main.milo_ps2 in \char\funkgh1\anims\gen while working on gh1 characters in gh2. (read funkgh1 as funk1, they are duplicates and do work) Isolating the issue down, I unpack the milo, then repack with no edits of the milo's contents, and gh2 will no longer load the character in game. Attempting to load the character freezes during the loading screen. In the PCSX2 program log, this error shows and pops up every few seconds while the game is stalled 
```
padman: DMA Busy ID = 4b110008 ret = 0
        SB_STAT = f0000102
```

If I restore the unedited milo, the character will again load.
I am unpacking the milo and repacking both with no flags set. Latest version 0.0.152 Windows x64
Ex.

`superfreq milo2dir "B:\gh\game_env\GEN\ext_dir\char\funkgh1\anims\gen\funkgh1_main.milo_ps2" "B:\gh\game_env\GEN\ext_dir\char\funkgh1\anims\gen\unpack\funkgh1_main" `

`superfreq dir2milo "B:\gh\game_env\GEN\ext_dir\char\funkgh1\anims\gen\unpack\funkgh1_main" "B:\gh\game_env\GEN\ext_dir\char\funkgh1\anims\gen\funkgh1_main.milo_ps2"
`

**Comment by PikminGuts92** [comment]
Following the same steps with `char\funk1\anims\gen\funk1_main.milo_ps2`, I'm not able to reproduce this error. I recommend starting from a clean game dump and starting over. GH2 files are very tightly coupled. It could be any number of things causing your issue.

**Comment by jnackmclain** [comment]
I just tried again on freshly extracted retail files with Johnny. Same thing, unpack, change nothing, repack milo, build ark and iso.
This file was `char\punk1\anims\gen\punk1_main.milo_ps2`
This time several TLB misses popped up as well as the DMA Busy line. I am attaching my repacked milo [here](https://www.mediafire.com/file/1dtdmhzx70cpqdr/punk1_main.milo_ps2/file) for the moment, as well as the program log for PCSX2. I will set up a new build env on a second machine to see if I can reproduce there as well after I submit this comment.

While I know the packed size after compression isn't going to be exactly the same, the sizes are - 
The original milo is 2.78 MB (2,915,735 bytes)
The repacked milo is 2.77 MB (2,914,276 bytes)
![image](https://user-images.githubusercontent.com/55568980/126236769-ca92c820-0afa-4c4b-b5fe-dd19dee2baf1.png)

**Comment by PikminGuts92** [comment]
Per the added label, I need more information. What release of GH2 is this (I tested on NTSC retail), PCSX2 version (I tested on EX v3.00.5), how did you repack the ark, how to did you rebuild iso, etc?

**Comment by PikminGuts92** [comment]
Oh wait. I'm seeing the issue now. It didn't immediately become noticeable last time I tried. I suspect it has to do with how its objects are sorted when serialized given that's the only difference between the two archives.

**Comment by jnackmclain** [comment]
Gotcha, I see your latest comment, but for full information

GH2 NTSC retail
unpacking with arkhelper ark2dir with -a and -s flags
unpacking milo with superfreq and no flags
repack with superfreq no flags
pack ark with arkhelper ark2dir and flags  -n "MAIN" -s 4073741823
built iso with imgburn for testing (how I always do for emu testing while milo hacking)
PCSX2 v1.7.0-dev-1259-g7efa96c73
BIOS USA v01.60

**Comment by PikminGuts92** [comment]
I added both `CharClipGroup` and `CharClipSamples` types, among others, to my list for ordering objects by type. Was able to play through two songs using the repacked milo without any issues. Please download and try out v153 and confirm it fixes your error. Once I hear back it works I'll close out this issue and put out an official GitHub release for once.

**Comment by jnackmclain** [comment]
Confirmed, I repacked the initial funk_main milo that started the issue with the new version. No longer hangs on load and no more DMA error lines. Thank you very much for the quick fix!
